name: Update GitHub Stats

on:
  schedule:
    - cron: 0 0 * * * # Runs daily at midnight

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub markdown

    - name: Generate GitHub Stats
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        python github_stats.py

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions-bot@example.com'
        git add README.md
        git commit -m "Update GitHub Stats" || echo "No changes to commit"
        git push